version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: singlehtml
  configuration: docs/conf.py
python:
   version: 3.7
   conda:
      environment: environment.yml
   install:
      - requirements: requirements.txt
      - method: pip
        path: .
